BaseURL = "http://rick.cogley.info"
canonifyurls = "false"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) License. Some rights reserved by James R. Cogley"
title = "Rick Cogley Central"
disqusShortname = "rickcogley" # Optional, enable Disqus integration
MetaDataFormat = "yaml"
paginate = 7

[author]
    name = "Rick Cogley"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:section/:slug"

[taxonomies]
  tag = "tags"
  topic = "topics"
  series = "series"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    description = "RCC is Rick Cogley Central, a site about Life in Japan, System Administration and Tech."
    keywords = "Cogley,Japan,Project,Help,IT,Web,Sysadmin"
    # Used when a given page doesn't set its own.
    defaultDescription = "A post by Rick Cogley"
    defaultKeywords = "cogley,post"
    highlightStyle = "solarized_dark"
    thumbnail = "/img/rick-cogley-avatar-90x90.png"
    sidebartitle = "RC Central"
    sidebartagline = "Welcome to Rick Cogley's site. Create, don't just consume."
    ISO8601 = "2006-01-02T15:04:05JST"

    # Metadata used to drive integrations.
    googleAuthorship = "+RickCogley"
    googleAnalytics = "UA-1040233-5"
    gravatarHash = "42f19a567cf937b98d2ab4cc09918461"

    # Reminder social links, which should be added to each md file.
    authorgithub = "https://github.com/rickcogley"
    authorlinkedin = "http://www.linkedin.com/in/rickcogley"
    authorgoogleplus = "https://plus.google.com/+RickCogley/posts"
    authorfacebook = "https://www.facebook.com/rickcogley"
    authortwitter = "https://twitter.com/rickcogley"

    # Blurbs to pull onto taxo pages
    postsblurb = "Wherein we catalog a most excellent list of pithy-yet-informative articles on tech, productivity, Japan, business and whatever else strikes our fancy. Please link the articles in your own postings."
    topicsblurb = "These are the high-level topics discussed on this site. Please link the articles in your own postings."
    tagsblurb = "These are the tags used to focus attention on the content of this site. Please link the articles in your own postings."


    # Try a comment block
    headercommentblock = "\u003c\u0021\u002d\u002d\n              \u005f\u005f\u005f\u005f\u005f                    \u005f\u005f\u005f\u005f\u005f                    \u005f\u005f\u005f\u005f\u005f          \n             \u002f\u005c    \u005c                  \u002f\u005c    \u005c                  \u002f\u005c    \u005c         \n            \u002f\u003a\u003a\u005c    \u005c                \u002f\u003a\u003a\u005c    \u005c                \u002f\u003a\u003a\u005c    \u005c        \n            \u005c\u003a\u003a\u003a\u005c    \u005c              \u002f\u003a\u003a\u003a\u003a\u005c    \u005c              \u002f\u003a\u003a\u003a\u003a\u005c    \u005c       \n             \u005c\u003a\u003a\u003a\u005c    \u005c            \u002f\u003a\u003a\u003a\u003a\u003a\u003a\u005c    \u005c            \u002f\u003a\u003a\u003a\u003a\u003a\u003a\u005c    \u005c      \n              \u005c\u003a\u003a\u003a\u005c    \u005c          \u002f\u003a\u003a\u003a\u002f\u005c\u003a\u003a\u003a\u005c    \u005c          \u002f\u003a\u003a\u003a\u002f\u005c\u003a\u003a\u003a\u005c    \u005c     \n               \u005c\u003a\u003a\u003a\u005c    \u005c        \u002f\u003a\u003a\u003a\u002f\u005f\u005f\u005c\u003a\u003a\u003a\u005c    \u005c        \u002f\u003a\u003a\u003a\u002f  \u005c\u003a\u003a\u003a\u005c    \u005c    \n               \u002f\u003a\u003a\u003a\u003a\u005c    \u005c      \u002f\u003a\u003a\u003a\u003a\u005c   \u005c\u003a\u003a\u003a\u005c    \u005c      \u002f\u003a\u003a\u003a\u002f    \u005c\u003a\u003a\u003a\u005c    \u005c   \n      \u005f\u005f\u005f\u005f\u005f   \u002f\u003a\u003a\u003a\u003a\u003a\u003a\u005c    \u005c    \u002f\u003a\u003a\u003a\u003a\u003a\u003a\u005c   \u005c\u003a\u003a\u003a\u005c    \u005c    \u002f\u003a\u003a\u003a\u002f    \u002f \u005c\u003a\u003a\u003a\u005c    \u005c  \n     \u002f\u005c    \u005c \u002f\u003a\u003a\u003a\u002f\u005c\u003a\u003a\u003a\u005c    \u005c  \u002f\u003a\u003a\u003a\u002f\u005c\u003a\u003a\u003a\u005c   \u005c\u003a\u003a\u003a\u005c\u005f\u005f\u005f\u005f\u005c  \u002f\u003a\u003a\u003a\u002f    \u002f   \u005c\u003a\u003a\u003a\u005c    \u005c \n    \u002f\u003a\u003a\u005c    \u002f\u003a\u003a\u003a\u002f  \u005c\u003a\u003a\u003a\u005c\u005f\u005f\u005f\u005f\u005c\u002f\u003a\u003a\u003a\u002f  \u005c\u003a\u003a\u003a\u005c   \u005c\u003a\u003a\u003a\u007c    \u007c\u002f\u003a\u003a\u003a\u002f\u005f\u005f\u005f\u005f\u002f     \u005c\u003a\u003a\u003a\u005c\u005f\u005f\u005f\u005f\u005c\n    \u005c\u003a\u003a\u003a\u005c  \u002f\u003a\u003a\u003a\u002f    \u005c\u003a\u003a\u002f    \u002f\u005c\u003a\u003a\u002f   \u007c\u003a\u003a\u003a\u003a\u005c  \u002f\u003a\u003a\u003a\u007c\u005f\u005f\u005f\u005f\u007c\u005c\u003a\u003a\u003a\u005c    \u005c      \u005c\u003a\u003a\u002f    \u002f\n     \u005c\u003a\u003a\u003a\u005c\u002f\u003a\u003a\u003a\u002f    \u002f \u005c\u002f\u005f\u005f\u005f\u005f\u002f  \u005c\u002f\u005f\u005f\u005f\u005f\u007c\u003a\u003a\u003a\u003a\u003a\u005c\u002f\u003a\u003a\u003a\u002f    \u002f  \u005c\u003a\u003a\u003a\u005c    \u005c      \u005c\u002f\u005f\u005f\u005f\u005f\u002f \n      \u005c\u003a\u003a\u003a\u003a\u003a\u003a\u002f    \u002f                 \u007c\u003a\u003a\u003a\u003a\u003a\u003a\u003a\u003a\u003a\u002f    \u002f    \u005c\u003a\u003a\u003a\u005c    \u005c             \n       \u005c\u003a\u003a\u003a\u003a\u002f    \u002f                  \u007c\u003a\u003a\u007c\u005c\u003a\u003a\u003a\u003a\u002f    \u002f      \u005c\u003a\u003a\u003a\u005c    \u005c            \n        \u005c\u003a\u003a\u002f    \u002f                   \u007c\u003a\u003a\u007c \u005c\u003a\u003a\u002f\u005f\u005f\u005f\u005f\u002f        \u005c\u003a\u003a\u003a\u005c    \u005c           \n         \u005c\u002f\u005f\u005f\u005f\u005f\u002f                    \u007c\u003a\u003a\u007c  \u007e\u007c               \u005c\u003a\u003a\u003a\u005c    \u005c          \n                                    \u007c\u003a\u003a\u007c   \u007c                \u005c\u003a\u003a\u003a\u005c    \u005c         \n                                    \u005c\u003a\u003a\u007c   \u007c                 \u005c\u003a\u003a\u003a\u005c\u005f\u005f\u005f\u005f\u005c        \n                                     \u005c\u003a\u007c   \u007c                  \u005c\u003a\u003a\u002f    \u002f        \n                                      \u005c\u007c\u005f\u005f\u005f\u007c                   \u005c\u002f\u005f\u005f\u005f\u005f\u002f         \n                                                                               \n\u002d\u002d\u003e\n"

    [[menu.main]]
        name = "Blog"
        url = "/post"

    [[menu.main]]
        name = "About"
        url = "/about"

    [[menu.social]]
        pre = "<i class='fa fa-twitter'></i>"
        url = "http://www.twitter.com/rickcogley"
        identifier = "twitter"
        weight = 1

    [[menu.social]]
        pre = "<i class='fa fa-google-plus'></i>"
        url = "https://plus.google.com/+RickCogley?rel=author"
        identifier = "google-plus"
        weight = 2

    [[menu.social]]
        pre = "<i class='fa fa-facebook'></i>"
        url = "https://www.facebook.com/rickcogley"
        identifier = "facebook"
        weight = 3

    [[menu.social]]
        pre = "<i class='fa fa-linkedin-square'></i>"
        url = "http://www.linkedin.com/in/rickcogley"
        identifier = "linkedin"
        weight = 4

    [[menu.social]]
        pre = "<i class='fa fa-camera-retro'></i>"
        url = "http://500px.com/rickcogley"
        identifier = "500px"
        weight = 5

    [[menu.social]]
        pre = "<i class='fa fa-flickr'></i>"
        url = "http://www.flickr.com/photos/rickcogley/"
        identifier = "flickr"
        weight = 6

    [[menu.social]]
        pre = "<i class='fa fa-vimeo-square'></i>"
        url = "https://vimeo.com/rickcogley"
        identifier = "vimeo"
        weight = 7

    [[menu.social]]
        pre = "<i class='fa fa-youtube'></i>"
        url = "http://www.youtube.com/user/rickcogley?sub_confirmation=1"
        identifier = "youtube"
        weight = 8

    [[menu.social]]
        pre = "<i class='fa fa-adn'></i>"
        url = "https://alpha.app.net/rickcogley"
        identifier = "app dot net"
        weight = 9

    [[menu.social]]
        pre = "<i class='fa fa-github'></i>"
        url = "https://github.com/RickCogley"
        identifier = "github"
        weight = 10

    [[menu.social]]
        pre = "<i class='fa fa-thumb-tack'></i>"
        url = "https://pinboard.in/u:rickcogley"
        identifier = "pinboard"
        weight = 11

    [[menu.social]]
        pre = "<i class='fa fa-rss'></i>"
        url = "/index.xml"
        identifier = "rss"
        weight = 12

    [[menu.footer]]
        name = "Blog"
        url = "/post"

    [[menu.footer]]
        name = "My Firm eSolia Inc"
        url = "http://esolia.com"
